export const getRouteHome = () => '/'
export const getRouteLoan = () => '/loan'
export const getRouteProduct = () => '/product'
export const getRouteAccount = () => '/account'
export const getRouteResources = () => '/resources'
export const getRouteOnlineBank = () => '/online-bank'
export const getRouteNotFound = () => '*'

export const getRouteCareer = () => '/career'
export const getRouteSupport = () => '/support'
export const getRouteInvestors = () => '/investors'
export const getRouteAnalytics = () => '/analytics'
export const getRouteRequisites = () => '/requisites'
export const getRoutePressCenter = () => '/press-center'
export const getRouteAskAndQuestion = () => '/help/ask-and-question'
export const getRouteAbout = () => '/about'
export const getRouteQualityOfService = () => '/about/quality-of-service'
export const getRouteBusinessAndProcesses = () => '/about/business-and-processes'
export const getRouteCopmlianceAndBusinessEthics = () =>
  '/about/compliance-and-business-ethics'
