export { Header } from './Header'
export { Footer } from './Footer'
export { PageError } from './PageError'
export { PageLoader } from './PageLoader'

export { Intro } from './Intro'
export { Features } from './Features'
export { Exchange } from './Exchange'
export { World } from './World'
export { News } from './News'
export { Subscribe } from './Subscribe'

export { Suggestion } from './Suggestion'
export { Info } from './Info'
export { Instruction } from './Instruction'
export { Prescoring } from './Prescoring'

export { PaymentSchedule } from './PaymentSchedule'
export { SigningOfDocuments } from './SigningOfDocuments'
export { Confirmation } from './Confirmation'
export { Congratulations } from './Congratulations'
export { Denied } from './Denied'
